### ISSUE TITLE
Valid sites fail with 'DecodingError'

### ISSUE THREAD

**Issue by wspear** [AlexMili/Reachable#8] opened 2024-11-18 18:27 UTC
This project is just what I needed! But I found that I'm getting numerous false positives with the error_name 'DecodingError' and status_code -1. Most (maybe all?) sourceforge sites fail this way along with a variety of others. Here are a few valid sites where I'm seeing this behavior:

https://3proxy.org/
https://sourceforge.net/projects/sevenzip/
https://www.tddft.org/programs/APE/ (I just noticed that this seems to be a redirect to a bogus site)
https://password-hashing.net/
https://leenissen.dk/fann/wp/ects/bbmap/
https://i3wm.org/

For now I'm just going to treat 'DecodingError' as a success but it'd be nice if reachable was able to determine the status of these sites correctly.

**Comment by AlexMili** [comment] 2024-11-19 22:43
Thank you for your feedback!

After a quick investigation the problem is related to ZStandard decompression bugging for an unknown reason on httpx side. I tested on Python 3.8 and it works fine but not on Python 3.11. Which version of Python are you using ?

In the mean time, you can fix the error by setting `Accept-encoding` header with other encodings like gzip or brotli:
```python
from reachable import is_reachable
from reachable.client import Client


client = Client(headers={"Accept-encoding": "gzip br"}, include_host=True)

is_reachable("https://www.password-hashing.net/", client=client)

client.close()

```

**Comment by wspear** [comment] 2024-11-20 03:27
This is running Python@3.12.3, courtesy of Ubuntu 24.04.

**Comment by AlexMili** [comment] 2024-11-22 09:33
Ok thanks, created an issue on httpx: https://github.com/encode/httpx/issues/3411

**Comment by AlexMili** [comment] 2024-11-28 21:05
httpx `0.28.0` just has been published with the fix. Closing this issue.

**Closed as completed by AlexMili** 2024-11-28 21:05 UTC
Labels: bug
